name: Validate declarations

on:
  push:
  pull_request:
    types: [ opened, reopened ]

jobs:
  validate_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run test:schema

  validate_modified_declarations:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: |
          if [ -z $GITHUB_HEAD_REF ]; then BRANCH=$GITHUB_REF_NAME; else BRANCH=$GITHUB_HEAD_REF; fi
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 # fetch all history for all branches and tags
      - run: git checkout --force -B $BRANCH refs/remotes/origin/$BRANCH
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run test:modified
